"""Initial migration

Revision ID: 0385939c16e5
Revises: 
Create Date: 2024-03-20 22:05:43.097107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0385939c16e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Continent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Ville',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=35), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=35), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=45), nullable=False),
    sa.Column('Continent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Continent_id'], ['Continent.id'], ),
    sa.PrimaryKeyConstraint('id', 'Continent_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_user', sa.String(length=120), nullable=False),
    sa.Column('pseudo_user', sa.String(length=64), nullable=False),
    sa.Column('password_user', sa.String(length=128), nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_role'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_user'),
    sa.UniqueConstraint('pseudo_user')
    )
    op.create_table('Person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fonction', sa.String(length=45), nullable=False),
    sa.Column('nom', sa.String(length=45), nullable=False),
    sa.Column('nationalite_code', sa.String(length=45), nullable=False),
    sa.Column('Date_debut_mandat', sa.DateTime(), nullable=True),
    sa.Column('Date_fin', sa.DateTime(), nullable=True),
    sa.Column('parti', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['nationalite_code'], ['pays.id'], ),
    sa.PrimaryKeyConstraint('id', 'nationalite_code')
    )
    op.create_table('Depla_etranger_A',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('pays_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pays_id'], ['pays.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['Person.id'], ),
    sa.PrimaryKeyConstraint('id', 'person_id', 'pays_id')
    )
    op.create_table('Depla_etranger_F',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('pays_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pays_id'], ['pays.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['Person.id'], ),
    sa.PrimaryKeyConstraint('id', 'person_id', 'pays_id')
    )
    op.create_table('Mairie_Services',
    sa.Column('Person_id', sa.Integer(), nullable=True),
    sa.Column('ville_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_debut_service', sa.DateTime(), nullable=True),
    sa.Column('date_fin_service', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Person_id'], ['Person.id'], ),
    sa.ForeignKeyConstraint(['ville_id'], ['Ville.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Depla_domicile_F',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('ville_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('mairie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mairie_id'], ['Mairie_Services.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['Person.id'], ),
    sa.ForeignKeyConstraint(['ville_id'], ['Ville.id'], ),
    sa.PrimaryKeyConstraint('id', 'person_id', 'ville_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Depla_domicile_F')
    op.drop_table('Mairie_Services')
    op.drop_table('Depla_etranger_F')
    op.drop_table('Depla_etranger_A')
    op.drop_table('Person')
    op.drop_table('users')
    op.drop_table('pays')
    op.drop_table('role')
    op.drop_table('Ville')
    op.drop_table('Continent')
    # ### end Alembic commands ###
