"""empty message

Revision ID: e1553c9b7394
Revises: 
Create Date: 2024-03-24 19:42:44.790364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1553c9b7394'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=35), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=35), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_user', sa.String(length=120), nullable=False),
    sa.Column('pseudo_user', sa.String(length=64), nullable=False),
    sa.Column('password_user', sa.String(length=128), nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_role'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_user'),
    sa.UniqueConstraint('pseudo_user')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('pseudo', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pseudo'], ['users.pseudo_user'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('users')
    op.drop_table('role')
    # ### end Alembic commands ###
